=begin
#Messaging

#Bandwidth's HTTP Messaging platform

The version of the OpenAPI document: 4.2.5

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

module OpenapiClient
  VERSION = '1.0.0'
end
