=begin
#Messaging

#Bandwidth's HTTP Messaging platform

The version of the OpenAPI document: 4.2.5

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::MessagesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MessagesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::MessagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MessagesApi' do
    it 'should create an instance of MessagesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::MessagesApi)
    end
  end

  # unit tests for create_message
  # Create Message
  # Endpoint for sending text messages and picture messages using V2 messaging.
  # @param account_id User&#39;s account ID
  # @param message_request 
  # @param [Hash] opts the optional parameters
  # @return [BandwidthMessage]
  describe 'create_message test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_messages
  # Get Messages
  # Gets a list of messages based on query parameters.
  # @param account_id User&#39;s account ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :message_id The ID of the message to search for. Special characters need to be encoded using URL encoding
  # @option opts [String] :source_tn The phone number that sent the message
  # @option opts [String] :destination_tn The phone number that received the message
  # @option opts [String] :message_status The status of the message. One of RECEIVED, QUEUED, SENDING, SENT, FAILED, DELIVERED, ACCEPTED, UNDELIVERED
  # @option opts [String] :message_direction The direction of the message. One of INBOUND, OUTBOUND
  # @option opts [String] :carrier_name The name of the carrier used for this message. Possible values include, but are not limited to, Verizon and TMobile. Special characters need to be encoded using URL encoding (i.e. AT&amp;T should be passed as AT%26T)
  # @option opts [String] :message_type The type of the message. One of mms, sms
  # @option opts [Integer] :error_code The error code of the message
  # @option opts [String] :from_date_time The start of the date range to search in ISO 8601 format. Uses the message receive time. The date range to search in is currently 14 days.
  # @option opts [String] :to_date_time The end of the date range to search in ISO 8601 format. Uses the message receive time. The date range to search in is currently 14 days.
  # @option opts [String] :page_token A base64 encoded value used for pagination of results
  # @option opts [Integer] :limit The maximum records requested in search result. Default 100. The sum of limit and after cannot be more than 10000
  # @return [BandwidthMessagesList]
  describe 'get_messages test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
