=begin
#Messaging

#Bandwidth's HTTP Messaging platform

The version of the OpenAPI document: 4.2.5

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

# Common files
require_relative 'openapi_client/api_client'
require_relative 'openapi_client/api_error'
require_relative 'openapi_client/version'
require_relative 'openapi_client/configuration'

# Models
require_relative 'openapi_client/models/bandwidth_callback_message'
require_relative 'openapi_client/models/bandwidth_message'
require_relative 'openapi_client/models/bandwidth_message_item'
require_relative 'openapi_client/models/bandwidth_messages_list'
require_relative 'openapi_client/models/deferred_result'
require_relative 'openapi_client/models/media'
require_relative 'openapi_client/models/message_request'
require_relative 'openapi_client/models/messaging_exception'
require_relative 'openapi_client/models/page_info'
require_relative 'openapi_client/models/tag'

# APIs
require_relative 'openapi_client/api/media_api'
require_relative 'openapi_client/api/messages_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
