name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        #os: [windows-2016, windows-2019, ubuntu-18.04, ubuntu-20.04]
        #ruby-version: [2.6, 2.7, 3.0]
        os: [windows-2016, ubuntu-18.04]
        ruby-version: [2.6, 3.0]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    
    - name: Install Packages
      run: bundle install

    - name: Test
      env:
        BW_ACCOUNT_ID: ${{ secrets.BW_ACCOUNT_ID }}
        BW_USERNAME: ${{ secrets.BW_USERNAME }}
        BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
        BW_VOICE_APPLICATION_ID: ${{ secrets.BW_VOICE_APPLICATION_ID }}
        BW_MESSAGING_APPLICATION_ID: ${{ secrets.BW_MESSAGING_APPLICATION_ID }}
        BW_NUMBER: ${{ secrets.BW_NUMBER }}
        USER_NUMBER: ${{ secrets.USER_NUMBER }}
        BASE_CALLBACK_URL: ${{ secrets.BASE_CALLBACK_URL }}
      run: ruby ./test/test.rb
